/* [A] 가입가능 월정액 상품 조회 — 상품유형 IPTV (IPTV (채널 월정액))
 * 파일: query_productList_iptv.sql  / 상품유형 선택값 → 파일 매핑은 monthlyPurchase_spec.md R1.2 참고
 * 원본: Monthly_Select_Query.txt (vibeContext/Reference/030_monthlyPurchase/Query/, 로컬 전용·추후 삭제)
 * 원본 대비 변경점: 원본 UNION 블록 중 GUBUN = 'IPTV' 블록만 사용
 *   - 서비스관리번호 하드코딩 → :svcMgmtNo / 주민법인일련번호 '802059' → (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo)
 *   - 상품명 조건 (:prdNm NULL/빈 값 = 전체), 정렬 NM_PRODUCT → ID_PRODUCT, 페이지 OFFSET/FETCH (Oracle 19c)
 * 바인드 변수: :svcMgmtNo, :prdNm, :offset ((페이지-1)*10), :pageSize (10)
 * 결과 컬럼: GUBUN, ID_PRODUCT, NM_PRODUCT, ID_PACKAGE, ID_PRODUCT_PAR, TP_PPM, AMT_PRICE(부가세 포함), PPM_FREE_JOIN_PERD_CD, AGMT_MNDT_YN
 */

/* ===== 목록 ===== */
SELECT * FROM (
      	
       SELECT 'IPTV' GUBUN      	
           , TO_CHAR(ID_PROD) ID_PRODUCT      	
           , TO_CHAR(NM_PROD) NM_PRODUCT      	
           , '' ID_PACKAGE      	
           , '' ID_PRODUCT_PAR      	
           , '' TP_PPM      	
           , TO_CHAR(TRUNC(AMT_SALE*1.1)) AMT_PRICE      	
           , TO_CHAR(PPM_FREE_JOIN_PERD_CD) PPM_FREE_JOIN_PERD_CD    	
           , 'N' AGMT_MNDT_YN         	
       FROM ( 	
           SELECT PROD.CHNL_PRD_ID ID_PROD, CHNL_PRD_NM NM_PROD, OLDPRD_PKG_CD AS CD_PACKAGE, '10' AS CD_TYPE,  NVL( PROD.SALE_PRC, 0)  AMT_SALE, PROD.PPM_FREE_JOIN_PERD_CD 	
           FROM   PD_CHNL_PRD_MST PROD 	
           INNER JOIN PD_CHNL_PRD_AGMT_DTS C ON PROD.CHNL_PRD_ID = C.CHNL_PRD_ID	
           WHERE    PROD.ADDN_PRD_YN = 'Y'	
           AND    PROD.ASIS_PRD_TYP_CD = '30'	
           AND    NVL(PROD.PRD_COMPO_CD,'10') <> '20'	
           AND    NVL( PROD.SALE_PRC, 0) > 0 	
           AND    TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS') BETWEEN PROD.SVC_FR_DT AND PROD.SVC_TO_DT 	
           AND    TO_NUMBER(PROD.OLDPRD_PKG_CD) > DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL)))	
           AND    NOT ( PROD.CHNL_PRD_ID IN ('PP21000042') AND DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL))) BETWEEN 35 AND 36 )	
           AND C.PRD_AGMT_PERD_CD = '0'	
        UNION      	
           SELECT PROD.CHNL_PRD_ID ID_PROD, CHNL_PRD_NM NM_PROD, NULL CD_PACKAGE, NULL CD_TYPE, NVL( PROD.SALE_PRC, 0) AMT_SALE, PROD.PPM_FREE_JOIN_PERD_CD 	
           FROM   PD_CHNL_PRD_MST PROD 	
           INNER JOIN PD_CHNL_PRD_AGMT_DTS C ON PROD.CHNL_PRD_ID = C.CHNL_PRD_ID	
           WHERE  PROD.CHNL_PRD_ID IN ('PP21000059')	
           AND    TO_NUMBER(PROD.OLDPRD_PKG_CD) > DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL)))	
           AND C.PRD_AGMT_PERD_CD = '0'	
           	
			UNION  	  	
			  SELECT PROD.CHNL_PRD_ID ID_PROD, PROD.CHNL_PRD_NM NM_PROD, OLDPRD_PKG_CD AS CD_PACKAGE, '10' AS CD_TYPE, NVL( PROD.SALE_PRC, 0) AMT_SALE, PROD.PPM_FREE_JOIN_PERD_CD     	  	
			  FROM   PD_CHNL_PRD_MST PROD	  	  	
           INNER JOIN PD_CHNL_PRD_AGMT_DTS C ON PROD.CHNL_PRD_ID = C.CHNL_PRD_ID	
			  WHERE  PROD.CHNL_PRD_ID IN ('PP21000038')   	  	
			  AND    1 = decode('2','2','1','3','1',NULL)   	  	
           AND    TO_NUMBER(PROD.OLDPRD_PKG_CD) > DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL)))	
           AND C.PRD_AGMT_PERD_CD = '0'	
        UNION 	
           SELECT DTS.PRD_PRC_ID ID_PROD, MST.PRD_NM NM_PROD, NULL CD_PACKAGE , NULL CD_TYPE, NVL( DTS.SALE_PRC, 0) AMT_SALE, MST.PPM_FREE_JOIN_PERD_CD  		
           FROM PD_PRD_PRC_DTS DTS 	
           INNER JOIN PD_PRD_MST MST ON DTS.PRD_GRP_ID = MST.PRD_GRP_ID AND DTS.PRD_ID = MST.PRD_ID 	
           INNER JOIN PD_PRD_AGMT_DTS C ON DTS.PRD_PRC_ID = C.PRD_PRC_ID	
           WHERE MST.PRD_TYP_CD = '35'	
           AND MST.ASIS_PRD_TYP_CD = '30'	
           AND TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS') BETWEEN MST.SVC_FR_DT AND MST.SVC_TO_DT 	
           AND    DTS.SALE_PRC > 0	
           AND    NOT ( DTS.PRD_PRC_ID IN ('2100000001') AND DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL))) BETWEEN 35 AND 36 )	
           AND C.PRD_AGMT_PERD_CD = '0'	
       UNION 	
           SELECT PROD.CHNL_PRD_ID ID_PROD, CHNL_PRD_NM ||'(UHD채널팩)' , NULL CD_PACKAGE, NULL CD_TYPE,  NVL( PROD.SALE_PRC, 0) AMT_SALE, PROD.PPM_FREE_JOIN_PERD_CD 		
           FROM   PD_CHNL_PRD_MST PROD, (SELECT * FROM IEMA_PROG WHERE CD_PROG_GRP = '000012' AND CD_PROG = '2') PROG 	
           , PD_CHNL_PRD_AGMT_DTS C	
           WHERE PROG.CD_PROG_DTL1 = PROD.CHNL_PRD_ID	
           AND  PROD.CHNL_PRD_ID = C.CHNL_PRD_ID	
           AND C.PRD_AGMT_PERD_CD = '0'	
           AND EXISTS (	
               SELECT 'A' FROM IESM_CUST_SVC 	
               WHERE TECH_MTHD_CD||ID_PROD = PROG.CD_PROG_DTL2	
               AND ID_CUST_SVC = :svcMgmtNo AND CTZ_CORP_SER_NUM = (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo)	
           )	
       )
			) T1
WHERE 1=1
    AND (:prdNm IS NULL OR UPPER(NM_PRODUCT) LIKE '%' || UPPER(:prdNm) || '%')
    AND NOT EXISTS (
                     SELECT 1 FROM IEMA_PROG T2
                     WHERE CD_PROG_GRP = '000036'
                       AND CD_PROG = 'T0004'
                       AND T1.ID_PRODUCT = T2.CD_PROG_DTL1)
ORDER BY NM_PRODUCT ASC, ID_PRODUCT ASC
OFFSET :offset ROWS FETCH NEXT :pageSize ROWS ONLY;

/* ===== 전체 건수 (목록과 같은 조건) ===== */
SELECT COUNT(*) AS TOTAL_CNT FROM (
SELECT * FROM (
      	
       SELECT 'IPTV' GUBUN      	
           , TO_CHAR(ID_PROD) ID_PRODUCT      	
           , TO_CHAR(NM_PROD) NM_PRODUCT      	
           , '' ID_PACKAGE      	
           , '' ID_PRODUCT_PAR      	
           , '' TP_PPM      	
           , TO_CHAR(TRUNC(AMT_SALE*1.1)) AMT_PRICE      	
           , TO_CHAR(PPM_FREE_JOIN_PERD_CD) PPM_FREE_JOIN_PERD_CD    	
           , 'N' AGMT_MNDT_YN         	
       FROM ( 	
           SELECT PROD.CHNL_PRD_ID ID_PROD, CHNL_PRD_NM NM_PROD, OLDPRD_PKG_CD AS CD_PACKAGE, '10' AS CD_TYPE,  NVL( PROD.SALE_PRC, 0)  AMT_SALE, PROD.PPM_FREE_JOIN_PERD_CD 	
           FROM   PD_CHNL_PRD_MST PROD 	
           INNER JOIN PD_CHNL_PRD_AGMT_DTS C ON PROD.CHNL_PRD_ID = C.CHNL_PRD_ID	
           WHERE    PROD.ADDN_PRD_YN = 'Y'	
           AND    PROD.ASIS_PRD_TYP_CD = '30'	
           AND    NVL(PROD.PRD_COMPO_CD,'10') <> '20'	
           AND    NVL( PROD.SALE_PRC, 0) > 0 	
           AND    TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS') BETWEEN PROD.SVC_FR_DT AND PROD.SVC_TO_DT 	
           AND    TO_NUMBER(PROD.OLDPRD_PKG_CD) > DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL)))	
           AND    NOT ( PROD.CHNL_PRD_ID IN ('PP21000042') AND DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL))) BETWEEN 35 AND 36 )	
           AND C.PRD_AGMT_PERD_CD = '0'	
        UNION      	
           SELECT PROD.CHNL_PRD_ID ID_PROD, CHNL_PRD_NM NM_PROD, NULL CD_PACKAGE, NULL CD_TYPE, NVL( PROD.SALE_PRC, 0) AMT_SALE, PROD.PPM_FREE_JOIN_PERD_CD 	
           FROM   PD_CHNL_PRD_MST PROD 	
           INNER JOIN PD_CHNL_PRD_AGMT_DTS C ON PROD.CHNL_PRD_ID = C.CHNL_PRD_ID	
           WHERE  PROD.CHNL_PRD_ID IN ('PP21000059')	
           AND    TO_NUMBER(PROD.OLDPRD_PKG_CD) > DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL)))	
           AND C.PRD_AGMT_PERD_CD = '0'	
           	
			UNION  	  	
			  SELECT PROD.CHNL_PRD_ID ID_PROD, PROD.CHNL_PRD_NM NM_PROD, OLDPRD_PKG_CD AS CD_PACKAGE, '10' AS CD_TYPE, NVL( PROD.SALE_PRC, 0) AMT_SALE, PROD.PPM_FREE_JOIN_PERD_CD     	  	
			  FROM   PD_CHNL_PRD_MST PROD	  	  	
           INNER JOIN PD_CHNL_PRD_AGMT_DTS C ON PROD.CHNL_PRD_ID = C.CHNL_PRD_ID	
			  WHERE  PROD.CHNL_PRD_ID IN ('PP21000038')   	  	
			  AND    1 = decode('2','2','1','3','1',NULL)   	  	
           AND    TO_NUMBER(PROD.OLDPRD_PKG_CD) > DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL)))	
           AND C.PRD_AGMT_PERD_CD = '0'	
        UNION 	
           SELECT DTS.PRD_PRC_ID ID_PROD, MST.PRD_NM NM_PROD, NULL CD_PACKAGE , NULL CD_TYPE, NVL( DTS.SALE_PRC, 0) AMT_SALE, MST.PPM_FREE_JOIN_PERD_CD  		
           FROM PD_PRD_PRC_DTS DTS 	
           INNER JOIN PD_PRD_MST MST ON DTS.PRD_GRP_ID = MST.PRD_GRP_ID AND DTS.PRD_ID = MST.PRD_ID 	
           INNER JOIN PD_PRD_AGMT_DTS C ON DTS.PRD_PRC_ID = C.PRD_PRC_ID	
           WHERE MST.PRD_TYP_CD = '35'	
           AND MST.ASIS_PRD_TYP_CD = '30'	
           AND TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS') BETWEEN MST.SVC_FR_DT AND MST.SVC_TO_DT 	
           AND    DTS.SALE_PRC > 0	
           AND    NOT ( DTS.PRD_PRC_ID IN ('2100000001') AND DECODE(:svcMgmtNo,NULL,-1,TO_NUMBER((SELECT FN_CD_SPEED_IPTV( :svcMgmtNo , (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo) ) FROM DUAL))) BETWEEN 35 AND 36 )	
           AND C.PRD_AGMT_PERD_CD = '0'	
       UNION 	
           SELECT PROD.CHNL_PRD_ID ID_PROD, CHNL_PRD_NM ||'(UHD채널팩)' , NULL CD_PACKAGE, NULL CD_TYPE,  NVL( PROD.SALE_PRC, 0) AMT_SALE, PROD.PPM_FREE_JOIN_PERD_CD 		
           FROM   PD_CHNL_PRD_MST PROD, (SELECT * FROM IEMA_PROG WHERE CD_PROG_GRP = '000012' AND CD_PROG = '2') PROG 	
           , PD_CHNL_PRD_AGMT_DTS C	
           WHERE PROG.CD_PROG_DTL1 = PROD.CHNL_PRD_ID	
           AND  PROD.CHNL_PRD_ID = C.CHNL_PRD_ID	
           AND C.PRD_AGMT_PERD_CD = '0'	
           AND EXISTS (	
               SELECT 'A' FROM IESM_CUST_SVC 	
               WHERE TECH_MTHD_CD||ID_PROD = PROG.CD_PROG_DTL2	
               AND ID_CUST_SVC = :svcMgmtNo AND CTZ_CORP_SER_NUM = (SELECT CTZ_CORP_SER_NUM FROM IESM_CUST_SVC WHERE ID_CUST_SVC = :svcMgmtNo)	
           )	
       )
			) T1
WHERE 1=1
    AND (:prdNm IS NULL OR UPPER(NM_PRODUCT) LIKE '%' || UPPER(:prdNm) || '%')
    AND NOT EXISTS (
                     SELECT 1 FROM IEMA_PROG T2
                     WHERE CD_PROG_GRP = '000036'
                       AND CD_PROG = 'T0004'
                       AND T1.ID_PRODUCT = T2.CD_PROG_DTL1)
);
